// <auto-generated />
using System;
using AMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AMS.DAL.Data.Migrations
{
    [DbContext(typeof(AMSDbContext))]
    [Migration("20190827030516_AMSDbInit")]
    partial class AMSDbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AMS.Models.Entitys.LogInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exception");

                    b.Property<string>("Level")
                        .HasMaxLength(128);

                    b.Property<string>("Message");

                    b.Property<string>("MessageTemplate");

                    b.Property<string>("Properties");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("AMS.Models.Entitys.MenuInModule", b =>
                {
                    b.Property<long>("MenuID");

                    b.Property<long>("Id");

                    b.Property<long>("ModuleID");

                    b.HasKey("MenuID");

                    b.ToTable("MenuInModule");
                });

            modelBuilder.Entity("AMS.Models.Entitys.MenuInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("MenuPic")
                        .HasMaxLength(50);

                    b.Property<int>("MenuType");

                    b.Property<long>("ParentID");

                    b.Property<int?>("SortIndex");

                    b.Property<int>("Status");

                    b.Property<string>("Url")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("MenuInfo");
                });

            modelBuilder.Entity("AMS.Models.Entitys.RoleInMenu", b =>
                {
                    b.Property<long>("RoleId");

                    b.Property<long>("MenuId");

                    b.Property<long>("Id");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleInMenu");
                });

            modelBuilder.Entity("AMS.Models.Entitys.RoleInModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ModuleID");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleInModule");
                });

            modelBuilder.Entity("AMS.Models.Entitys.RoleInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<long>("CreateUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(20);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("RoleInfo");
                });

            modelBuilder.Entity("AMS.Models.Entitys.UserInRole", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.Property<long>("Id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserInRole");
                });

            modelBuilder.Entity("AMS.Models.Entitys.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreateUserID");

                    b.Property<DateTime>("CreateUserTime");

                    b.Property<int>("Gender");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .HasMaxLength(32);

                    b.Property<int>("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("UserPic")
                        .HasMaxLength(100);

                    b.Property<int>("UserType");

                    b.Property<string>("WorkUnit")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            Id = 1511L,
                            CreateUserID = 0L,
                            CreateUserTime = new DateTime(2019, 8, 27, 11, 5, 16, 253, DateTimeKind.Local).AddTicks(3916),
                            Gender = 0,
                            Password = "123456",
                            Status = 0,
                            UserName = "admin",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("AMS.Models.Entitys.MenuInModule", b =>
                {
                    b.HasOne("AMS.Models.Entitys.MenuInfo", "MenuInfo")
                        .WithMany("Modules")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AMS.Models.Entitys.RoleInMenu", b =>
                {
                    b.HasOne("AMS.Models.Entitys.MenuInfo", "MenuInfo")
                        .WithMany("Roles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AMS.Models.Entitys.RoleInfo", "RoleInfo")
                        .WithMany("Menus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AMS.Models.Entitys.RoleInModule", b =>
                {
                    b.HasOne("AMS.Models.Entitys.RoleInfo", "RoleInfo")
                        .WithMany("Modules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AMS.Models.Entitys.UserInRole", b =>
                {
                    b.HasOne("AMS.Models.Entitys.RoleInfo", "RoleInfo")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AMS.Models.Entitys.UserInfo", "UserInfo")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
